FROM php:apache-bullseye
RUN echo "=> Installiere Updates, aktualisiere Paketquellen und installiere Pakete"
RUN apt update && apt upgrade -y && apt autoremove -y && \
    apt install ca-certificates apt-transport-https gnupg libfreetype6-dev libjpeg62-turbo-dev libzip-dev libpng-dev -y && \
    apt update && \
    docker-php-ext-configure gd \
        --with-freetype \
        --with-jpeg && \
        docker-php-ext-install gd zip mysqli
RUN echo "=> Gebe den Port 80 frei"
EXPOSE 80
RUN echo "=> Setze das Verzeichnis frei für die Web-Dateien"
RUN a2enmod rewrite && service apache2 restart
VOLUME /var/www/html
